#!/usr/bin/bash


/usr/bin/rsync -avzhP /mnt/sda4/ /mnt/butter/ --delete

getStatus=$(systemctl status backup.service | grep -e "backup.service:" -e sent -e total | cut -d':' -f4-10)

echo -e "to: example@gmail.com\nSubject:Secondary File sync successfully completed on $(hostname).\n\n$getStatus" | /usr/sbin/sendmail -t -f root
